package frontend;

import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;

/**
 *
 * @author michael
 */
public class EditorPanel extends javax.swing.JPanel {

    private JTabbedPane pestaña;
    private JPanel ventana;
    private JTextArea areaTexto;
    
    NumeroLinea numerarEditor;
    NumeroLinea numerarConsola;
    /**
     * Creates new form EditorPanel
     */
    public EditorPanel() {
        initComponents();
        numerarEditor = new NumeroLinea(areaEditor);
        scrollEditor.setRowHeaderView(numerarEditor);
        numerarConsola = new NumeroLinea(areaConsola);
        scrollConsola.setRowHeaderView(numerarConsola);
        pestaña = new JTabbedPane();
    }
    
    public void setAreaEditor(String linea){
        areaEditor.setText(linea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelEditor = new javax.swing.JPanel();
        scrollEditor = new javax.swing.JScrollPane();
        areaEditor = new javax.swing.JTextArea();
        consolaPanel = new javax.swing.JPanel();
        scrollConsola = new javax.swing.JScrollPane();
        areaConsola = new javax.swing.JTextArea();
        ejecutarBoton = new javax.swing.JButton();
        limpiarBoton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new java.awt.GridBagLayout());

        panelEditor.setPreferredSize(new java.awt.Dimension(887, 500));
        panelEditor.setLayout(new java.awt.BorderLayout());

        areaEditor.setColumns(20);
        areaEditor.setRows(5);
        scrollEditor.setViewportView(areaEditor);

        panelEditor.add(scrollEditor, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 887;
        gridBagConstraints.ipady = 348;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 3);
        add(panelEditor, gridBagConstraints);

        areaConsola.setEditable(false);
        areaConsola.setColumns(20);
        areaConsola.setRows(5);
        scrollConsola.setViewportView(areaConsola);

        javax.swing.GroupLayout consolaPanelLayout = new javax.swing.GroupLayout(consolaPanel);
        consolaPanel.setLayout(consolaPanelLayout);
        consolaPanelLayout.setHorizontalGroup(
            consolaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consolaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollConsola, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
                .addContainerGap())
        );
        consolaPanelLayout.setVerticalGroup(
            consolaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consolaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollConsola, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 859;
        gridBagConstraints.ipady = 132;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 6, 1);
        add(consolaPanel, gridBagConstraints);

        ejecutarBoton.setBackground(new java.awt.Color(0, 255, 0));
        ejecutarBoton.setFont(new java.awt.Font("MesloLGL Nerd Font", 3, 12)); // NOI18N
        ejecutarBoton.setForeground(new java.awt.Color(0, 0, 0));
        ejecutarBoton.setText("Ejecutar");
        ejecutarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarBotonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 798, 0, 0);
        add(ejecutarBoton, gridBagConstraints);

        limpiarBoton.setBackground(new java.awt.Color(153, 153, 153));
        limpiarBoton.setFont(new java.awt.Font("MesloLGL Nerd Font", 0, 13)); // NOI18N
        limpiarBoton.setForeground(new java.awt.Color(0, 0, 0));
        limpiarBoton.setText("Limpiar Editor");
        limpiarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarBotonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 496, 0, 1);
        add(limpiarBoton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void ejecutarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarBotonActionPerformed
        areaConsola.setText("No se ha implementado lógica\n\nPrueba funcionamiento consola");
    }//GEN-LAST:event_ejecutarBotonActionPerformed

    private void limpiarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarBotonActionPerformed
        areaEditor.setText("");
        areaConsola.setText("");
    }//GEN-LAST:event_limpiarBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaConsola;
    private javax.swing.JTextArea areaEditor;
    private javax.swing.JPanel consolaPanel;
    private javax.swing.JButton ejecutarBoton;
    private javax.swing.JButton limpiarBoton;
    private javax.swing.JPanel panelEditor;
    private javax.swing.JScrollPane scrollConsola;
    private javax.swing.JScrollPane scrollEditor;
    // End of variables declaration//GEN-END:variables

       
    
    public void pintarPanel(Component panel) {
        panelEditor.removeAll();
        panelEditor.add(panel);
        panelEditor.repaint();
        panelEditor.revalidate();
    }
}
