@startuml diagramadeclases

class Main {

}

package analizador {

    package controladores {

        class ControlAnalizador {
            - Escaneable scanner
            - Parseable parser
            - ControlTablaSimbolo tablaSimbolos
            - ControladorError error
            + setFuente(String path): boolean
            + hacerAnalisis(): boolean
            + getArbolSintactico(): ArbolSintactico
            + esError(): boolean
            + getErrores(): Error
            getTablaSimbolos(): TablaSimbolo
        }

        class ControladorError {
            - Error error
        }

        package parser {

            enum ParserFactory {
                +getParser(): Parseable
            }

            interface Parseable {
                + getToken(): Token
                + esFinalArchivo(): boolean
                + leerArchivo(): boolean
            }

            package controladorpythonparser {
                class PythonParser {
                    - ControladorFuncionTrancicion ControladorFuncionTrancicion
                    - numero linea
                    - numero columna
                    - String path
                    - String contenido
                }

                class ControladorEstadoAceptacion {
                    + getEstadoAceptacion(Estado estado): TipoToken

                }

                class ControladorFuncionTrancicion {
                    - Estado[][] matrizEstados
                    + delta(Estado estado, SimboloAlfabeto simbolo): Estado
                }

                class ControladorSimboloAlfabeto {
                    + isCaracterTerminal(): boolean
                    + getTipoAlfabeto(char caracter): SimboloAlfabeto
                }

                PythonParser *-- ControladorFuncionTrancicion
                PythonParser --> ControladorEstadoAceptacion
                PythonParser --> ControladorSimboloAlfabeto
            }

            PythonParser -up-|> Parseable
            ParserFactory .left.> Parseable


        }

        ControlAnalizador *-- Parseable
        ControlAnalizador ..> ParserFactory

        Escaneable -right-> Parseable: getToken
    }

    package modelos {

        class Token {
            - TipoToken tipoToken
            - int linea
            - int columna
            - String path
        }

        enum TipoToken {

        }

        package modelospythonparser {
            enum Estado {
                + ESTADO1
                + ESTADO2
            }

            class EstadoAceptacion {
                - List<Estado> estadoAceptacion
                + getEstadoAceptacion(): List<Estado>
            }

            enum SimboloAlfabeto {
                + digito
                + letras
            }
        }

        Token *-- TipoToken

    }


    Parseable ..> Token
    ControladorEstadoAceptacion --> EstadoAceptacion
    ControladorEstadoAceptacion --> TipoToken
    ControladorFuncionTrancicion *-- Estado
    ControladorFuncionTrancicion ..> SimboloAlfabeto
    ControladorSimboloAlfabeto ..> SimboloAlfabeto

}

package util {
    class AdministradorArchivos {
        + String leerArchivoTexto(String path): String
    }
}

Parseable  ..>AdministradorArchivos
Main .down.> ControlAnalizador

@enduml

