@startuml diagramadeclases

class Main {

}

package analizador {

    package controladores {

        class ControlAnalizador {
            - Escaneable scanner
            - Parseable parser
            - ControlTablaSimbolo tablaSimbolos
            - ControladorError error
            + setFuente(String path): boolean
            + hacerAnalisis(): boolean
            + getArbolSintactico(): ArbolSintactico
            + esError(): boolean
            + getErrores(): Error
            getTablaSimbolos(): TablaSimbolo
        }

        class ControlTablaSimbolo {
            - TablaSimbolo tablaSimbolo
        }

        class ControladorError {
            - Error error
        }

        package scanner {

            class ScannerFactory {

            }

            class ControladorArbolSintactico {
                - ArbolSintactico arbolSintactico
            }

            interface Escaneable{
                + {abstract} setParser(Parseable parser)
                + {abstract} boolean verificarGramatica()
                + {abstract} setTablasimbolos(ControlTablaSimbolo controlTablaSimbolo)
                + {abstract} ArbolSintactico getArbolSintactico()
            }

            class AutomataPila {

            }

            AutomataPila -up-|> Escaneable
            Escaneable *-- ControladorArbolSintactico
            ScannerFactory .right.> ControlAnalizador
        }

        package parser {

            class ParserFactory {

            }

            interface Parseable {
                + {abstract} boolean setFuente(String path)
                + {abstract} setTablasimbolos(ControlTablaSimbolo controlTablaSimbolo)
            }

            class AutomataFinito {

            }

            AutomataFinito -up-|> Parseable
        }

        ControlAnalizador *-- Parseable
        ControlAnalizador *-- Escaneable
        ControlAnalizador *-- ControlTablaSimbolo
        ControlAnalizador *-- ControladorError
        ControlAnalizador ..> ParserFactory
        ParserFactory .left.> Parseable

        Escaneable -right-> Parseable
    }

    package modelos {

        class Error {

        }

        class ArbolSintactico {

        }

        class TablaSimbolo {

        }

        class Token {
            - TipoToken tipoToken
        }

        enum TipoToken {

        }

        Token *-- TipoToken

    }

    ControlTablaSimbolo *-down- TablaSimbolo
    ControladorError *-- Error

    ControladorArbolSintactico *-- ArbolSintactico

}

Main .down.> ControlAnalizador

@enduml

